[build]
publish = "public"
command = "npm run build"

[[redirects]]
  from = "http://rachelbourgeois-psychologue.netlify.app/*"
  to = "https://rachelbourgeois-psychologue.netlify.app/:splat"
  status = 301
  force = true